import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import ReactQueryProvider from '@/providers/ReactQueryProivder';

const inter = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400'],
});

export const metadata: Metadata = {
  title: ' Users Management App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
